<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class profileSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $ProfileRecords = [
            [
                "id" => 1,
                "user_id" => 1,
                "city_live" => "Gujranwala",
                "live_family" => "Pakaistan",
                "marital_status" => "Never Mrried",
                "diet" => "Veg",
                "height" => "5-9feet",
                "sub_community" => "Rajpoot",
                "high_education" => "Graduation",
                "work_with" => "Softwa Company",
                "designation" => "Manager",
                "salary" => "5Lac",
                "current_company" => "virtual",
                "college_name" => "Virtual",
                "bio" => "Engineer with some years",
                "country_code" => "+92",
                "mobile_number" => "0900786011",
                "disability" => "No",
                "blood_group" => "A+",
                "father_status" => "Bussiness Man",
                "mother_status" => "House Wife",
                "family_location" => "Pakistan",
                "native_place" => "Pakistan",
                "siblings" => "5",
                "no_of_sisters" => "3",
                "no_of_brothers" => "2",
                "family_type" => "broad Minded",
                "family_values" => "Broad",
                "family_affluence" => "Broad",
                
                
            ],

            [
                "id" => 2,
                "user_id" => 2,
                "city_live" => "Isblamabad",
                "live_family" => "Pakaistan",
                "marital_status" => "Mrried",
                "diet" => "Veg",
                "height" => "5-9feet",
                "sub_community" => "Rajpoot",
                "high_education" => "FSC",
                "work_with" => "Sales Company",
                "designation" => "Sales Man",
                "salary" => "5Lac",
                "current_company" => "virtual",
                "college_name" => "Virtual",
                "bio" => "I am a Sales Man",
                "country_code" => "+92",
                "mobile_number" => "0900786011",
                "disability" => "No",
                "blood_group" => "A+",
                "father_status" => "Sales Man",
                "mother_status" => "House Wife",
                "family_location" => "Pakistan",
                "native_place" => "Pakistan",
                "siblings" => "3",
                "no_of_sisters" => "1",
                "no_of_brothers" => "2",
                "family_type" => "broad Minded",
                "family_values" => "Broad",
                "family_affluence" => "Broad",
                
                
            ],

            [
                "id" => 3,
                "user_id" => 3,
                "city_live" => "Isblamabad",
                "live_family" => "Pakaistan",
                "marital_status" => "Never Married",
                "diet" => "Non-Veg",
                "height" => "5-9feet",
                "sub_community" => "Mughal",
                "high_education" => "Master",
                "work_with" => "Sales Company",
                "designation" => "Manager",
                "salary" => "10Lac",
                "current_company" => "virtual",
                "college_name" => "Virtual",
                "bio" => "I am a Sales Man",
                "country_code" => "+92",
                "mobile_number" => "0900786011",
                "disability" => "No",
                "blood_group" => "A+",
                "father_status" => "Sales Man",
                "mother_status" => "House Wife",
                "family_location" => "Pakistan",
                "native_place" => "Pakistan",
                "siblings" => "4",
                "no_of_sisters" => "2",
                "no_of_brothers" => "2",
                "family_type" => "broad Minded",
                "family_values" => "Broad",
                "family_affluence" => "Broad",
                
                
            ],

            [
                "id" => 4,
                "user_id" => 4,
                "city_live" => "Multan",
                "live_family" => "Pakaistan",
                "marital_status" => "Never Married",
                "diet" => "Non-Veg",
                "height" => "5-9feet",
                "sub_community" => "Arain",
                "high_education" => "Master",
                "work_with" => "Sales Company",
                "designation" => "Manager",
                "salary" => "10Lac",
                "current_company" => "virtual",
                "college_name" => "Virtual",
                "bio" => "I am a Sales Man",
                "country_code" => "+92",
                "mobile_number" => "0900786011",
                "disability" => "No",
                "blood_group" => "A+",
                "father_status" => "Sales Man",
                "mother_status" => "House Wife",
                "family_location" => "Pakistan",
                "native_place" => "Pakistan",
                "siblings" => "4",
                "no_of_sisters" => "2",
                "no_of_brothers" => "2",
                "family_type" => "broad Minded",
                "family_values" => "Broad",
                "family_affluence" => "Broad",
                
                
            ],

            [
                "id" => 5,
                "user_id" => 5,
                "city_live" => "Lahore",
                "live_family" => "Pakaistan",
                "marital_status" => "Never Married",
                "diet" => "Veg",
                "height" => "5-6feet",
                "sub_community" => "Mughal",
                "high_education" => "Master",
                "work_with" => "Sales Company",
                "designation" => "Manager",
                "salary" => "10Lac",
                "current_company" => "virtual",
                "college_name" => "Virtual",
                "bio" => "I am a Sales Man",
                "country_code" => "+92",
                "mobile_number" => "0900786011",
                "disability" => "No",
                "blood_group" => "A+",
                "father_status" => "Sales Man",
                "mother_status" => "House Wife",
                "family_location" => "Pakistan",
                "native_place" => "Pakistan",
                "siblings" => "4",
                "no_of_sisters" => "2",
                "no_of_brothers" => "2",
                "family_type" => "broad Minded",
                "family_values" => "Broad",
                "family_affluence" => "Broad",
                
                
            ],

            [
                "id" => 6,
                "user_id" => 6,
                "city_live" => "Saudia Arabia",
                "live_family" => "Pakaistan",
                "marital_status" => "Never Married",
                "diet" => "Veg",
                "height" => "5-11feet",
                "sub_community" => "Mughal",
                "high_education" => "Graduation",
                "work_with" => "Privte Company",
                "designation" => "Manager",
                "salary" => "10Lac",
                "current_company" => "virtual",
                "college_name" => "Virtual",
                "bio" => "I am working in a Private Comapany",
                "country_code" => "+92",
                "mobile_number" => "0900786011",
                "disability" => "No",
                "blood_group" => "A+",
                "father_status" => "Sales Man",
                "mother_status" => "House Wife",
                "family_location" => "Pakistan",
                "native_place" => "Pakistan",
                "siblings" => "4",
                "no_of_sisters" => "2",
                "no_of_brothers" => "2",
                "family_type" => "broad Minded",
                "family_values" => "Broad",
                "family_affluence" => "Broad",
                
                
            ],

            [
                "id" => 7,
                "user_id" => 7,
                "city_live" => "UAE",
                "live_family" => "Pakaistan",
                "marital_status" => "Married",
                "diet" => "Veg",
                "height" => "4-11feet",
                "sub_community" => "Mughal",
                "high_education" => "Graduation",
                "work_with" => "Privte Company",
                "designation" => "Manager",
                "salary" => "10Lac",
                "current_company" => "virtual",
                "college_name" => "Virtual",
                "bio" => "I am working in a Private Comapany",
                "country_code" => "+92",
                "mobile_number" => "0900786011",
                "disability" => "No",
                "blood_group" => "A+",
                "father_status" => "Sales Man",
                "mother_status" => "House Wife",
                "family_location" => "Pakistan",
                "native_place" => "Pakistan",
                "siblings" => "4",
                "no_of_sisters" => "2",
                "no_of_brothers" => "2",
                "family_type" => "broad Minded",
                "family_values" => "Broad",
                "family_affluence" => "Broad",
                
                
            ],

            [
                "id" => 8,
                "user_id" => 8,
                "city_live" => "UAE",
                "live_family" => "Pakaistan",
                "marital_status" => "Married",
                "diet" => "Veg",
                "height" => "4-11feet",
                "sub_community" => "Mughal",
                "high_education" => "Graduation",
                "work_with" => "Privte Company",
                "designation" => "Manager",
                "salary" => "10Lac",
                "current_company" => "virtual",
                "college_name" => "Virtual",
                "bio" => "I am working in a Private Comapany",
                "country_code" => "+92",
                "mobile_number" => "0900786011",
                "disability" => "No",
                "blood_group" => "A+",
                "father_status" => "Sales Man",
                "mother_status" => "House Wife",
                "family_location" => "Pakistan",
                "native_place" => "Pakistan",
                "siblings" => "4",
                "no_of_sisters" => "2",
                "no_of_brothers" => "2",
                "family_type" => "broad Minded",
                "family_values" => "Broad",
                "family_affluence" => "Broad",
                
                
            ],

            [
                "id" => 9,
                "user_id" => 9,
                "city_live" => "Gujranwala",
                "live_family" => "Pakaistan",
                "marital_status" => "Never Mrried",
                "diet" => "Veg",
                "height" => "5-9feet",
                "sub_community" => "Rajpoot",
                "high_education" => "Graduation",
                "work_with" => "Softwa Company",
                "designation" => "Manager",
                "salary" => "5Lac",
                "current_company" => "virtual",
                "college_name" => "Virtual",
                "bio" => "Engineer with some years",
                "country_code" => "+92",
                "mobile_number" => "0900786011",
                "disability" => "No",
                "blood_group" => "A+",
                "father_status" => "Bussiness Man",
                "mother_status" => "House Wife",
                "family_location" => "Pakistan",
                "native_place" => "Pakistan",
                "siblings" => "5",
                "no_of_sisters" => "3",
                "no_of_brothers" => "2",
                "family_type" => "broad Minded",
                "family_values" => "Broad",
                "family_affluence" => "Broad",
                
                
            ],

            [
                "id" => 10,
                "user_id" => 10,
                "city_live" => "Gujranwala",
                "live_family" => "Pakaistan",
                "marital_status" => "Mrried",
                "diet" => "Veg",
                "height" => "5-9feet",
                "sub_community" => "Rajpoot",
                "high_education" => "Graduation",
                "work_with" => "Softwa Company",
                "designation" => "Manager",
                "salary" => "5Lac",
                "current_company" => "virtual",
                "college_name" => "Virtual",
                "bio" => "Engineer with some years",
                "country_code" => "+92",
                "mobile_number" => "0900786011",
                "disability" => "No",
                "blood_group" => "A+",
                "father_status" => "Bussiness Man",
                "mother_status" => "House Wife",
                "family_location" => "Pakistan",
                "native_place" => "Pakistan",
                "siblings" => "5",
                "no_of_sisters" => "3",
                "no_of_brothers" => "2",
                "family_type" => "broad Minded",
                "family_values" => "Broad",
                "family_affluence" => "Broad",
                
                
            ],

            [
                "id" => 11,
                "user_id" => 11,
                "city_live" => "Islamabad",
                "live_family" => "Pakaistan",
                "marital_status" => "Never Mrried",
                "diet" => "Veg",
                "height" => "5-9feet",
                "sub_community" => "Mughal",
                "high_education" => "Graduation",
                "work_with" => "Softwa Company",
                "designation" => "Manager",
                "salary" => "5Lac",
                "current_company" => "virtual",
                "college_name" => "Virtual",
                "bio" => "Engineer with some years",
                "country_code" => "+92",
                "mobile_number" => "0900786011",
                "disability" => "No",
                "blood_group" => "A+",
                "father_status" => "Bussiness Man",
                "mother_status" => "House Wife",
                "family_location" => "Pakistan",
                "native_place" => "Pakistan",
                "siblings" => "5",
                "no_of_sisters" => "3",
                "no_of_brothers" => "2",
                "family_type" => "broad Minded",
                "family_values" => "Broad",
                "family_affluence" => "Broad",
                
                
            ],

            [
                "id" => 12,
                "user_id" => 12,
                "city_live" => "Multan",
                "live_family" => "Pakaistan",
                "marital_status" => "Never Mrried",
                "diet" => "Veg",
                "height" => "5-9feet",
                "sub_community" => "Mughal",
                "high_education" => "Graduation",
                "work_with" => "Softwa Company",
                "designation" => "Manager",
                "salary" => "5Lac",
                "current_company" => "virtual",
                "college_name" => "Virtual",
                "bio" => "Engineer with some years",
                "country_code" => "+92",
                "mobile_number" => "0900786011",
                "disability" => "No",
                "blood_group" => "A+",
                "father_status" => "Bussiness Man",
                "mother_status" => "House Wife",
                "family_location" => "Pakistan",
                "native_place" => "Pakistan",
                "siblings" => "5",
                "no_of_sisters" => "3",
                "no_of_brothers" => "2",
                "family_type" => "broad Minded",
                "family_values" => "Broad",
                "family_affluence" => "Broad",
                
                
            ],
        ];


        // Saving user
        DB::table('profiles')->insert($ProfileRecords);
    }
}
